
const JELLIT={phone:'5541987142736',email:'jefferson.s.santospop@gmail.com',site:'https://SEU-USUARIO.github.io/jellit-site/',emailjs:{enabled:false,serviceId:'SEU_SERVICE_ID',templateId:'SEU_TEMPLATE_ID',publicKey:'SUA_PUBLIC_KEY'}};
const serviceMessages={bug:'Olá Jefferson. Tenho um bug em Java/Spring Boot e preciso de ajuda urgente. Pode avaliar?',api:'Olá Jefferson. Preciso desenvolver ou ajustar uma API REST em Spring Boot. Pode me passar um orçamento?',micro:'Olá Jefferson. Preciso de apoio com microsserviços Java/Spring Boot. Pode avaliar meu cenário?',kafka:'Olá Jefferson. Preciso de ajuda com Kafka/eventos/mensageria em uma aplicação Java. Pode me ajudar?',aws:'Olá Jefferson. Preciso de suporte com AWS/deploy/arquitetura cloud para Java. Pode avaliar?',arquitetura:'Olá Jefferson. Preciso de uma revisão de arquitetura Java/microsserviços. Pode me ajudar?',review:'Olá Jefferson. Preciso de code review técnico em Java/Spring Boot. Pode me passar uma proposta?',mentoria:'Olá Jefferson. Quero uma mentoria/consultoria Java, Spring Boot ou arquitetura. Pode me explicar como funciona?',geral:'Olá Jefferson. Vi o site da Jellit e gostaria de falar sobre uma demanda técnica.'};
function wa(key='geral'){return `https://wa.me/${JELLIT.phone}?text=${encodeURIComponent(serviceMessages[key]||serviceMessages.geral)}`}
function bindWhats(){document.querySelectorAll('[data-wa]').forEach(a=>a.href=wa(a.dataset.wa));}
function nav(){const btn=document.querySelector('.mobile-toggle'),menu=document.querySelector('.menu'); if(btn&&menu)btn.addEventListener('click',()=>menu.classList.toggle('open'))}
function contact(){const f=document.querySelector('#contactForm'); if(!f)return; f.addEventListener('submit', async e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(f).entries()); const honey=data.website; if(honey){return} const txt=`Olá Jefferson. Meu nome é ${data.name||''}. Assunto: ${data.service||'Contato geral'}. Mensagem: ${data.message||''}. Email: ${data.email||''}`; window.open(`https://wa.me/${JELLIT.phone}?text=${encodeURIComponent(txt)}`,'_blank'); document.querySelector('#formStatus').textContent='Mensagem preparada no WhatsApp com segurança. Para e-mail direto, configure o EmailJS no js/app.js.';});}
function reveal(){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.card,.step,.timeline-item').forEach(el=>{el.style.opacity=.001;el.style.transform='translateY(18px)';el.style.transition='600ms ease';obs.observe(el)});const s=document.createElement('style');s.textContent='.visible{opacity:1!important;transform:none!important}';document.head.appendChild(s)}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
document.addEventListener('DOMContentLoaded',()=>{bindWhats();nav();contact();reveal();});
